### ISSUE TITLE
Can I work on redesigning the site?

### ISSUE THREAD

**Issue by wbrijesh** [EddieHubCommunity/EddieHubCommunity.github.io#106]
The site currently isn't that great, can I work on redesigning it?

**Comment by BOLT04** [comment]
Hi @wbrijesh 😃, we value all contributions to the project. Can you go into more detail on how you are planning on redesigning it? We would like this to be broken down into steps if the resulting PR is too big.

**Comment by wbrijesh** [comment]
Maybe making it look a little bit modern, and more clear. 
I'll just create and link a figma design which you can see before i actually start building it.

**Comment by wbrijesh** [comment]
check out https://www.figma.com/proto/qSVbO6T8Bg2vHGdyCK7LeU/eddie-jaoude-community-redesign?node-id=1%3A2&scaling=min-zoom&hide-ui=1

**Comment by eddiejaoude** [comment]
Its great you created a Figma design first as it gives a starting point for us all to discuss 👍 . 

<img width="1394" alt="Screenshot 2020-10-25 at 14 17 20" src="https://user-images.githubusercontent.com/624760/97109757-f4bb7f00-16cc-11eb-9ed0-043a75ecd4b4.png">

**Comment by wbrijesh** [comment]
I have not worked on many sites apart for myself or side-projects, so please freely give any opinions you may have.

**Comment by wbrijesh** [comment]
Do you have any suggestions?

**Comment by eddiejaoude** [comment]
I would suggest making the changes slowly and incremental. For example update the hero banner to look like your design only. So to make the PRs as small as possible and to provide value to the users as quickly as possible

**Comment by BOLT04** [comment]
Hi @wbrijesh, sorry for not being active lately. But I saw your design on Figma and it looks great 👍 
I agree 100% with @eddiejaoude 😃. Create a issue for each piece you want to work on, then make a PR. The smaller it is, the faster it'll get merged.

> Do you have any suggestions?

I'd keep the icons for the footer (e.g. GitHub and Youtube icon). Also it's not clear on a Figma design, but keeping some animation on hover of these buttons would be good as well.
I'm not sure about moving the moderators part to the top of the page, since we lose some information we currently have. However I think it does look good on your design. I was thinking we could use this right section of the hero banner (I think that is what it's called 😅) with another image of some other info, to reflect the whole community... but bear in mind, I'm just thinking "out loud" here 😃 .

Here are my suggestions on the tasks to do:
- [ ] Create the initial navigation bar (that doesn't exist currently)
   - [ ] Add the Eddie logo perhaps and the text "Eddie Jaoude Community"
   - [ ] Add the CTA on the right to join the community
- [ ] Redesign hero banner
- [ ] Redesign projects section
- [ ] Redesign Footer

Hope that helps 😃

**Comment by BOLT04** [comment]
oh @wbrijesh and @eddiejaoude, I thought of an idea of something to put on that right side instead of an image or moderators 😃. What do you think of a video/gif that gets played after the page is loaded? I was thinking of those videos @eddiejaoude has on his README profile.

**Comment by eddiejaoude** [comment]
Great break down above, thanks @BOLT04  👍 

I do like video / gif 🤓 - what would it be showing?

**Comment by wbrijesh** [comment]
redesigning sections one after another makes sense, I will make these sections and start putting pull requests.

**Comment by wbrijesh** [comment]
If making a video is possible, that would be perfect for the site!

**Comment by BOLT04** [comment]
> I do like video / gif 🤓 - what would it be showing?

I only thought of some ideas 😅, like maybe show some of your youtube intros, then transition into showing PRs from the community, discussions, or really cool issues. Then maybe show the discord or EddieBotUI to show popular messages, and stuff that is shared on the community. Maybe a section with your live streams, for example the Github actions live stream with Brian, or the live stream where the community does open source.

**Comment by eddiejaoude** [comment]
I can create a video / gif, for now we could use a placeholder image, like the image we have on the side already

**Comment by wbrijesh** [comment]
Hi, I would like to know if you have any suggestion before i submit a pr

[https://www.figma.com/file/MDLemXcqEIjllsl5E2Lrvo/Untitled?node-id=0%3A1](url)

<img width="931" alt="Screenshot 2020-11-16 at 1 28 15 AM" src="https://user-images.githubusercontent.com/28498071/99195510-3317fb80-27ac-11eb-8737-287cda032070.png">

**Comment by wbrijesh** [comment]
I repeated the paragraph under 'we believe open source is for everyone' to fill little more space. I think there is room for improvement there in terms of length.

**Comment by BOLT04** [comment]
Hi @wbrijesh 😃, first of all great work on your design. I really like your suggestion and I think you can start working on your PR 👍. With that said, here are my thoughts:
- Maybe adding a slight bottom border on the navigation bar, with a darker color, indicates a better separation of the sections. What do you think?
- I'm thinking if having less text on that CTA to join the community is better, but I really like your idea on that button... and I'm no UI/UX expert so let's go with your idea since it's awesome 👍 😄 

Lastly, about what you said:
> I repeated the paragraph under 'we believe open source is for everyone' to fill little more space. I think there is room for improvement there in terms of length.

I actually think the smaller the paragraph is, the better 😃. The reason being I don't expect the user to spend that much time reading our header, but I'm not against having more content on that paragraph either. Maybe to make it easier to read we could have a bullet list or bold out some words.

**Comment by eddiejaoude** [comment]
Looks great @wbrijesh 👍

**Comment by eddiejaoude** [comment]
Thank you all for the great work! New website is now live (using a template), I will close this issue, any suggestions can come in a new issue
