### ISSUE TITLE
Failing UI tests

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/EddieHubCommunity.github.io#138]
Update Cypress Cucumber tests for the rename from `Eddie Jaoude` to `EddieHub`

https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/develop/cypress/integration/homepage.feature

**Comment by jai-dewani** [comment]
I am on it! 👀

**Comment by eddiejaoude** [comment]
Thanks 👍

**Comment by jai-dewani** [comment]
After fixing the issue, I was trying to run the tests locally before pushing the code. And it turns out that the tests are still failing because the data in [EddieHubCommunity.github.io/src/data.js](https://github.com/EddieHubCommunity/EddieHubCommunity.github.io/blob/develop/src/data.js) also needs to be updated in light of the recent change in name of the GitHub community. 

Going to create a new Issue for this and will push the updated tests but they will still fail until the links in `data.js` are not rectified

**Comment by eddiejaoude** [comment]
ok, thanks 👍

**Comment by eddiejaoude** [comment]
Thanks @jai-dewani . In your PRs can you have `fixes #123` at the top of the description and without the word `issue` in-between so that GitHub can auto close the PR
